import type { Project } from "@/lib/domain";

export function createGenerateTestProject(): Project {
  const slides = [
    {
      id: "slide-1",
      title: "Opening",
      purpose: "Introduce the idea",
      audienceTakeaway: "Judges understand the promise.",
      layout: "hero" as const,
      bullets: ["A clear opening"],
      visual: { type: "statement" as const, statement: "Evidence becomes a clear story." },
      narration: "This is the opening narration.",
      durationSeconds: 20,
      evidencePaths: ["README.md"],
    },
    {
      id: "slide-2",
      title: "Solution",
      purpose: "Explain the solution",
      audienceTakeaway: "Judges see the evidence-aware workflow.",
      layout: "solution" as const,
      bullets: ["A useful capability"],
      visual: {
        type: "flow" as const,
        steps: [{ label: "Evidence" }, { label: "Story" }, { label: "Impact" }],
      },
      narration: "This is the solution narration.",
      durationSeconds: 20,
      evidencePaths: ["src/app.ts"],
    },
    {
      id: "slide-3",
      title: "Close",
      purpose: "Close the story",
      audienceTakeaway: "Judges know the next step.",
      layout: "closing" as const,
      bullets: ["A memorable close"],
      visual: { type: "statement" as const, statement: "Move the idea forward." },
      narration: "This is the closing narration.",
      durationSeconds: 20,
      evidencePaths: [],
    },
  ];

  return {
    id: "project-1",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    stage: "create",
    input: {
      idea: "Turn repository evidence into a concise presentation.",
      audience: "Hackathon judges",
      tone: "confident",
      durationMinutes: 1,
      githubUrl: "https://github.com/example/project",
    },
    repository: {
      url: "https://github.com/example/project",
      owner: "example",
      repo: "project",
      commitSha: "abc123",
      description: "A fixture repository",
      languages: ["TypeScript"],
      evidence: [
        {
          path: "README.md",
          excerpt: "Repository evidence must remain user-provided context.",
          url: "https://github.com/example/project/blob/abc123/README.md",
          category: "readme",
        },
        {
          path: "src/app.ts",
          excerpt: "The application validates structured presentation output.",
          url: "https://github.com/example/project/blob/abc123/src/app.ts",
          category: "entry-point",
        },
      ],
    },
    revisions: [
      {
        id: "revision-1",
        version: 1,
        createdAt: "2026-01-01T00:00:00.000Z",
        title: "Fixture deck",
        tagline: "A fixture tagline",
        summary: "A fixture presentation used for Foundry contract tests.",
        strategy: {
          audienceGoal: "Help judges evaluate the idea quickly.",
          coreMessage: "Repository evidence becomes a credible presentation.",
          problem: "Implementation evidence is difficult to present concisely.",
          solution: "A typed workflow turns selected evidence into a clear story.",
          differentiators: ["Typed evidence-aware generation"],
          proofPoints: [{ claim: "The README documents the approach.", evidencePaths: ["README.md"] }],
          narrativeArc: ["hook", "problem", "solution", "close"],
          voiceoverDirection: "Add concise decision context.",
          demoPlan: { recommendation: "omit", rationale: "The fixture does not require a demo." },
        },
        slides,
        promptVersion: "presentation-v1",
        source: "foundry",
      },
    ],
    activeRevisionId: "revision-1",
    approvedPlanRevisionId: null,
    approvedDeckRevisionId: null,
    renderJobs: [],
    assets: [],
    lastError: null,
  };
}
